### ISSUE TITLE
Deploy error:  unsupported protocol scheme

### ISSUE THREAD

**Issue by gembin** [UKHomeOffice/drone-kubernetes#7]
Thanks a lot for this great plugin!
But, I got the following error when deploying, any help would be greatly appreciated.

```
[info] Pulling image quay.io/ukhomeofficedigital/drone-kubernetes:latest
2016/03/30 10:00:15 Get /: unsupported protocol scheme ""
[info] build failed (exit code 1)
```

.drone.yaml

``` yaml
deploy:
  kubernetes:
    image: quay.io/ukhomeofficedigital/drone-kubernetes
    replicationcontrollers: 
       - k8s/test-rc.yaml
    apiserver: http://172.17.4.101:8080
    namespace: default
```

The k8s/test-rc.yaml is located in the source directory. 

```
├── Dockerfile
├── LICENSE
├── README.md
├── k8s
│   └── test-rc.yaml
├── pom.xml
└── src
```
